[package]
name = "sccc"
version = "0.1.0"
authors = ["Marcus Xu <xumarcus.sg@gmail.com>"]
edition = "2021"

[workspace]
members = [
    "crates/cc",
    "crates/lexer",
]

[dependencies]
cc = { path = "crates/cc" }
lexer = { path = "crates/lexer" }
